/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const CareerPath = IDL.Record({
  'title' : IDL.Text,
  'collegeRecommendations' : IDL.Vec(IDL.Text),
  'skillMap' : IDL.Vec(IDL.Text),
});
export const QuizResult = IDL.Record({
  'recommendedJob' : IDL.Text,
  'careerScore' : IDL.Vec(IDL.Nat),
  'resultId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const QuizAnswer = IDL.Record({
  'questionId' : IDL.Nat,
  'selectedOption' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func([Question], [], []),
  'fetchAiResponse' : IDL.Func(
      [IDL.Text, IDL.Vec(Header), IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllCareerPaths' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
  'getPredefinedPath' : IDL.Func([IDL.Nat], [CareerPath], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuizResult' : IDL.Func([IDL.Principal], [QuizResult], ['query']),
  'getUserAnswers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'hasQuizResults' : IDL.Func([], [IDL.Bool], ['query']),
  'submitAnswers' : IDL.Func([IDL.Vec(QuizAnswer), IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const CareerPath = IDL.Record({
    'title' : IDL.Text,
    'collegeRecommendations' : IDL.Vec(IDL.Text),
    'skillMap' : IDL.Vec(IDL.Text),
  });
  const QuizResult = IDL.Record({
    'recommendedJob' : IDL.Text,
    'careerScore' : IDL.Vec(IDL.Nat),
    'resultId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const QuizAnswer = IDL.Record({
    'questionId' : IDL.Nat,
    'selectedOption' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func([Question], [], []),
    'fetchAiResponse' : IDL.Func(
        [IDL.Text, IDL.Vec(Header), IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllCareerPaths' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
    'getPredefinedPath' : IDL.Func([IDL.Nat], [CareerPath], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuizResult' : IDL.Func([IDL.Principal], [QuizResult], ['query']),
    'getUserAnswers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'hasQuizResults' : IDL.Func([], [IDL.Bool], ['query']),
    'submitAnswers' : IDL.Func([IDL.Vec(QuizAnswer), IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };