/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerPath {
  'title' : string,
  'collegeRecommendations' : Array<string>,
  'skillMap' : Array<string>,
}
export interface Header { 'value' : string, 'name' : string }
export interface Question {
  'id' : bigint,
  'text' : string,
  'options' : Array<string>,
}
export interface QuizAnswer { 'questionId' : bigint, 'selectedOption' : bigint }
export interface QuizResult {
  'recommendedJob' : string,
  'careerScore' : Array<bigint>,
  'resultId' : string,
  'timestamp' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addQuestion' : ActorMethod<[Question], undefined>,
  'fetchAiResponse' : ActorMethod<[string, Array<Header>, string], string>,
  'getAllCareerPaths' : ActorMethod<[], Array<CareerPath>>,
  'getPredefinedPath' : ActorMethod<[bigint], CareerPath>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getQuizResult' : ActorMethod<[Principal], QuizResult>,
  'getUserAnswers' : ActorMethod<[], Array<string>>,
  'hasQuizResults' : ActorMethod<[], boolean>,
  'submitAnswers' : ActorMethod<[Array<QuizAnswer>, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];